// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using m5.Models;

namespace m5.Migrations
{
    [DbContext(typeof(MovieApplicationContext))]
    [Migration("20220202225241_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("m5.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoryname")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Categoryname = "Action/Adventure"
                        },
                        new
                        {
                            CategoryId = 2,
                            Categoryname = "Comedy"
                        },
                        new
                        {
                            CategoryId = 3,
                            Categoryname = "Drama"
                        },
                        new
                        {
                            CategoryId = 4,
                            Categoryname = "Family"
                        },
                        new
                        {
                            CategoryId = 5,
                            Categoryname = "Horror/Suspense"
                        },
                        new
                        {
                            CategoryId = 6,
                            Categoryname = "Miscellaneous"
                        },
                        new
                        {
                            CategoryId = 7,
                            Categoryname = "Television"
                        },
                        new
                        {
                            CategoryId = 8,
                            Categoryname = "VHS"
                        });
                });

            modelBuilder.Entity("m5.Models.FormResponse", b =>
                {
                    b.Property<int>("FormID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FormID");

                    b.HasIndex("CategoryId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            FormID = 1,
                            CategoryId = 1,
                            Director = "Joss Whedon",
                            Edited = false,
                            LentTo = "Haneul Song",
                            Notes = "For date",
                            Rating = "PG-13",
                            Title = "Avengers, The",
                            Year = "2012"
                        },
                        new
                        {
                            FormID = 2,
                            CategoryId = 1,
                            Director = "Christoper Nolan",
                            Edited = false,
                            LentTo = "Morgan Jin",
                            Notes = "For fun",
                            Rating = "PG-13",
                            Title = "Dark Knight, The",
                            Year = "2008"
                        },
                        new
                        {
                            FormID = 3,
                            CategoryId = 1,
                            Director = "The Wachowski Brothers",
                            Edited = false,
                            LentTo = "Henry Cho",
                            Notes = "For fun",
                            Rating = "R",
                            Title = "Matrix, The",
                            Year = "1999"
                        });
                });

            modelBuilder.Entity("m5.Models.FormResponse", b =>
                {
                    b.HasOne("m5.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
